Update windows_amd64.yml

diff --git a/.github/workflows/windows_amd64.yml b/.github/workflows/windows_amd64.yml
--- a/.github/workflows/windows_amd64.yml
+++ b/.github/workflows/windows_amd64.yml
@@ -17,14 +17,6 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v2
 
-      - name: Load Chocolatey cache
-        id: choco-cache
-        uses: actions/cache@v2
-        with:
-          path: C:\ProgramData\chocolatey\lib
-          key: choco-packages-${{ runner.os }}
-          restore-keys: choco-packages-
-
       - name: Set up JDK 17
         uses: actions/setup-java@v2
         with:
@@ -36,46 +28,6 @@ jobs:
 
       - name: Install Visual Studio Build Tools
         run: choco install -y visualstudio2019-workload-vctools
-
-      - name: Set up Windows SDK 10 environment
-        shell: powershell
-        run: |
-          $vsPath = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools"
-          $vcvarsPath = Join-Path -Path $vsPath -ChildPath "VC\\Auxiliary\\Build\\vcvars64.bat"
-          $windowsSdk10Path = "C:\\Program Files (x86)\\Windows Kits\\10"
-
-          if (Test-Path $vcvarsPath) {
-            Write-Host "Setting up Visual Studio Build Tools environment..."
-            cmd.exe /C "`"$vcvarsPath`" && set"
-          }
-          else {
-            Write-Error "vcvars64.bat not found in Visual Studio Build Tools installation directory."
-            exit 1
-          }
-
-          if (Test-Path $windowsSdk10Path) {
-            Write-Host "Setting up Windows SDK 10 environment..."
-            cmd.exe /C "set PATH=%PATH%;`"$windowsSdk10Path\\bin`""
-            cmd.exe /C "set INCLUDE=%INCLUDE%;`"$windowsSdk10Path\\include`""
-            cmd.exe /C "set LIB=%LIB%;`"$windowsSdk10Path\\lib`""
-          }
-          else {
-            Write-Error "Windows SDK 10 not found in the default installation directory."
-            exit 1
-          }
-
-      - name: Verify Visual Studio Build Tools environment variables
-        run: |
-          echo "PATH=$env:PATH"
-          echo "INCLUDE=$env:INCLUDE"
-          echo "LIB=$env:LIB"
-
-      - name: Cache Chocolatey packages
-        uses: actions/cache@v2
-        with:
-          path: C:\ProgramData\chocolatey\lib
-          key: choco-packages-${{ runner.os }}
-          restore-keys: choco-packages-
 
       - name: Build the project using Gradle
         run: ./gradlew.bat build
@@ -98,6 +50,31 @@ jobs:
             echo "GRAAL_HOME=$env:GRAAL_HOME"
             echo "NATIVE_IMAGE=$env:NATIVE_IMAGE"
             echo "CC_PACKAGED_JAR=$env:CC_PACKAGED_JAR"
+
+            $vsPath = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools"
+            $vcvarsPath = Join-Path -Path $vsPath -ChildPath "VC\\Auxiliary\\Build\\vcvars64.bat"
+            $windowsSdk10Path = "C:\\Program Files (x86)\\Windows Kits\\10"
+
+            if (Test-Path $vcvarsPath) {
+              Write-Host "Setting up Visual Studio Build Tools environment..."
+              cmd.exe /C "`"$vcvarsPath`" && set"
+            }
+            else {
+              Write-Error "vcvars64.bat not found in Visual Studio Build Tools installation directory."
+              exit 1  
+            }
+
+            if (Test-Path $windowsSdk10Path) {
+              Write-Host "Setting up Windows SDK 10 environment..."
+              cmd.exe /C "set PATH=%PATH%;`"$windowsSdk10Path\\bin`""
+              cmd.exe /C "set INCLUDE=%INCLUDE%;`"$windowsSdk10Path\\include`""
+              cmd.exe /C "set LIB=%LIB%;`"$windowsSdk10Path\\lib`""
+            }
+            else {
+              Write-Error "Windows SDK 10 not found in the default installation directory."
+              exit 1
+            }
+
 
             & $env:NATIVE_IMAGE -jar $env:CC_PACKAGED_JAR `
             -H:Name=Cloudchains-SPV `
