Update windows_amd64.yml

diff --git a/.github/workflows/windows_amd64.yml b/.github/workflows/windows_amd64.yml
--- a/.github/workflows/windows_amd64.yml
+++ b/.github/workflows/windows_amd64.yml
@@ -20,9 +20,8 @@ jobs:
       - name: Setup Java
         uses: actions/setup-java@v2
         with:
-          distribution: 'temurin'
+          distribution: 'adopt'
           java-version: '17'
-          cache: 'gradle'
 
       - name: Install Visual Studio Build Tools 2019
         uses: ilammy/msvc-dev-cmd@v1
@@ -30,17 +29,26 @@ jobs:
           vs-path: '2019'
 
       - name: Install Windows SDK 10
-        run: choco install windows-sdk-10 -y
-
-      - name: Create environment file
         run: |
-          echo "SDK_PATH=C:\Program Files (x86)\Windows Kits\10" >> $GITHUB_ENV
-          echo "PATH=$env:SDK_PATH\bin;$env:PATH" >> $GITHUB_ENV
-          echo "LIB=$env:SDK_PATH\Lib;$env:LIB" >> $GITHUB_ENV
-          echo "INCLUDE=$env:SDK_PATH\Include;$env:INCLUDE" >> $GITHUB_ENV
+          choco install windows-sdk-10 -y
+
+      - name: Set Windows SDK path
+        run: |
+          echo "::set-env name=SDK_PATH::C:\Program Files (x86)\Windows Kits\10"
+          echo "::add-path::$env:SDK_PATH\bin"
+          echo "::add-path::$env:SDK_PATH\Lib"
+          echo "::add-path::$env:SDK_PATH\Include"
 
       - name: Build Native Image
-        run: ./gradlew.bat nativeImage --stacktrace
+        run: |
+          # Run the nativeImage task using the installed SDK
+          ./gradlew.bat nativeImage --stacktrace
+
+          # Check if the nativeImage task failed
+          if ($LASTEXITCODE -ne 0) {
+            Write-Error "Failed to build native image."
+            exit $LASTEXITCODE
+          }
 
       - name: Upload Artifacts
         uses: actions/upload-artifact@v2
